### ISSUE TITLE
Are subscription updates supported?

### ISSUE THREAD

**Issue by pervopertsa** [JonasKruckenberg/tauri-plugin-graphql#37]
First time a subscription is executed on the frontend it returns data and works fine but I'm unable to get any updates.

Reading the library code it looks like data from subscription handler stream is only read and emitted once after which the function returns, initially I thought that I must make my streams to never return `None` but instead that lead to the whole program freezing. I'm pretty new to rust and juniper but to me it seems like these currently implemented "subscriptions" are really more one-off events and updates are not supported. Is this correct?

**Comment by JonasKruckenberg** [comment]
If you look a [this line](https://github.com/JonasKruckenberg/tauri-plugin-graphql/blob/11d7cb604b14b17dec6160357276ec4e9f50a2e3/src/lib.rs#L394)you can see that the plugin in fact reads and emits the stream items  asynchronously so yes subscriptions are fully supported.

What you meant is that the handler returns only once, but it returns a stream! The example in this repo is maybe a bit misleading in this regard, you would never construct a stream from a vec in real code. But you can construct a stream from a `tokio::mpsc` channel and suddenly this becomes much more useful.

```rust
use async_stream::wrappers:: ReceiverStream;

#[graphql_subscription(context = GraphQLContext)]
impl Subscription {
    async fn hello_world() -> StringStream {
       let (tx,rx) = tokio::mpsc::channel(16);

        tokio::spawn(async move {
        for i in 0..10 {
            if let Err(_) = tx.send(i).await {
                println!("receiver dropped");
                return;
            }
        }
    });



       Box::pin(ReceiverStream::new(rx))
    }
}

```

**Comment by pervopertsa** [comment]
Okay I see it was a problem with my subscription stream logic. I got it working now, thanks for pointing me in the right direction. Great library btw.
