### ISSUE TITLE
use async-graphql over juniper

### ISSUE THREAD

**Issue by Suyashtnt** [JonasKruckenberg/tauri-plugin-graphql#63]
async-graphql is another gql framework for rust and overall, it seems to be better than juniper [according to their comparison](https://github.com/async-graphql/async-graphql/blob/master/feature-comparison.md). I'ved used both and async-graphql seems better to work with

**Comment by JonasKruckenberg** [comment]
Interesting! I actually wasn't aware of this `async-graphql` crate. I cannot promise anything however, as there are many projects that need attention and this would be s fairly substantial rewrite. I'm happy to review+accept a PR however!

**Comment by Suyashtnt** [comment]
> Interesting! I actually wasn't aware of this `async-graphql` crate. I cannot promise anything however, as there are many projects that need attention and this would be s fairly substantial rewrite. I'm happy to review+accept a PR however!

I might PR this for a better DX with the app I'm currently working on as duplicating types is really annoying rn. Subscriptions could also be very helpful with the app. I'll start making a PR soon

**Comment by JonasKruckenberg** [comment]
But the current version of the plugin has subscriptions too, just FIY. It's just hidden behind the `subscriptions` flag bc it adds another dependency.

**Comment by Suyashtnt** [comment]
> The current version of the plugin has subscriptions too, just FIY. It's just hidden behind the `subscriptions` flag bc it adds another dependency.

I know, I just prefer async-graphqls impl over juniper
